### ISSUE TITLE
Upload bug

### ISSUE THREAD

**Issue by io7m** [io7m-com/brooklime#19]
Something seems to be wrong with the upload process as of today:

```
brooklime: com.io7m.brooklime.cmdline.internal.BLCommandUploadToStagingRepository: INFO: [1/792] /home/runner/work/android-audiobook/android-audiobook/build/maven/org/thepalaceproject/audiobook/org.librarysimplified.audiobook.api/13.0.0-beta0017/org.librarysimplified.audiobook.api-13.0.0-beta0017-javadoc.jar: Started upload, attempt 1 of 25
brooklime: com.io7m.brooklime.cmdline.Main: ERROR: Wrote more data than expected (expected 261 but received 522)
java.lang.IllegalStateException: Wrote more data than expected (expected 261 but received 522)
	at com.io7m.brooklime.vanilla.internal.BLProgressCounter.addSizeReceived(BLProgressCounter.java:69)
	at com.io7m.brooklime.vanilla.internal.BLStreamEntity.writeTo(BLStreamEntity.java:84)
	at org.apache.hc.core5.http.impl.io.DefaultBHttpClientConnection.sendRequestEntity(DefaultBHttpClientConnection.java:153)
	at org.apache.hc.core5.http.impl.io.HttpRequestExecutor.execute(HttpRequestExecutor.java:148)
	at org.apache.hc.core5.http.impl.io.HttpRequestExecutor.execute(HttpRequestExecutor.java:225)
	at org.apache.hc.client5.http.impl.io.PoolingHttpClientConnectionManager$InternalConnectionEndpoint.execute(PoolingHttpClientConnectionManager.java:596)
	at org.apache.hc.client5.http.impl.classic.InternalExecRuntime.execute(InternalExecRuntime.java:220)
	at org.apache.hc.client5.http.impl.classic.MainClientExec.execute(MainClientExec.java:107)
	at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
	at org.apache.hc.client5.http.impl.classic.ExecChainElement$1.proceed(ExecChainElement.java:57)
	at org.apache.hc.client5.http.impl.classic.ConnectExec.execute(ConnectExec.java:181)
	at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
	at org.apache.hc.client5.http.impl.classic.ExecChainElement$1.proceed(ExecChainElement.java:57)
	at org.apache.hc.client5.http.impl.classic.ProtocolExec.execute(ProtocolExec.java:165)
	at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
	at org.apache.hc.client5.http.impl.classic.ExecChainElement$1.proceed(ExecChainElement.java:57)
	at org.apache.hc.client5.http.impl.classic.HttpRequestRetryExec.execute(HttpRequestRetryExec.java:93)
	at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
	at org.apache.hc.client5.http.impl.classic.ExecChainElement$1.proceed(ExecChainElement.java:57)
	at org.apache.hc.client5.http.impl.classic.RedirectExec.execute(RedirectExec.java:116)
	at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
	at org.apache.hc.client5.http.impl.classic.ExecChainElement$1.proceed(ExecChainElement.java:57)
	at org.apache.hc.client5.http.impl.classic.ContentCompressionExec.execute(ContentCompressionExec.java:128)
	at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
	at org.apache.hc.client5.http.impl.classic.InternalHttpClient.doExecute(InternalHttpClient.java:178)
	at org.apache.hc.client5.http.impl.classic.CloseableHttpClient.execute(CloseableHttpClient.java:75)
	at com.io7m.brooklime.vanilla.internal.BLRetryingUploader.execute(BLRetryingUploader.java:137)
	at com.io7m.brooklime.vanilla.internal.BLNexusRequests.upload(BLNexusRequests.java:410)
	at com.io7m.brooklime.vanilla.internal.BLNexusClient.upload(BLNexusClient.java:75)
	at com.io7m.brooklime.cmdline.internal.BLCommandUploadToStagingRepository.execute(BLCommandUploadToStagingRepository.java:145)
	at com.io7m.brooklime.cmdline.Main.run(Main.java:137)
	at com.io7m.brooklime.cmdline.Main.main(Main.java:107)
```

**Comment by io7m** [comment]
It's not clear that this needs to be an error. A warning might be sufficient. Why can this happen at all, though?

**Comment by io7m** [comment]
Affects: https://github.com/io7m-com/brooklime/issues/20
